#!/usr/bin/env bash
# Faelight Forest Theme Switcher
# Switches between dark and light themes system-wide
# Usage: theme-switch.sh [dark|light|toggle]

set -e

THEMES_DIR="$HOME/dotfiles/themes"
CURRENT_FILE="$THEMES_DIR/current.txt"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${CYAN}🌲 $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Get theme colors from JSON
get_color() {
    local theme=$1
    local key=$2
    jq -r ".colors.$key" "$THEMES_DIR/faelight-$theme/theme.json"
}

# Apply Hyprland theme
apply_hyprland() {
    local theme=$1
    log_info "Applying Hyprland theme..."
    
    local bg=$(get_color "$theme" "background")
    local border=$(get_color "$theme" "border")
    local border_active=$(get_color "$theme" "border_active")
    local primary=$(get_color "$theme" "primary")
    local secondary=$(get_color "$theme" "secondary")
    
    # Update Hyprland colors using hyprctl
    hyprctl keyword general:col.active_border "rgb(${border_active#\#})" >/dev/null
    hyprctl keyword general:col.inactive_border "rgb(${border#\#})" >/dev/null
    
    log_success "Hyprland themed"
}

# Apply Kitty theme
apply_kitty() {
    local theme=$1
    log_info "Applying Kitty theme..."
    
    local bg=$(get_color "$theme" "background")
    local text=$(get_color "$theme" "text")
    local primary=$(get_color "$theme" "primary")
    local secondary=$(get_color "$theme" "secondary")
    local accent=$(get_color "$theme" "accent")
    local comment=$(get_color "$theme" "comment")
    
    # Create/update Kitty theme config
    cat > ~/.config/kitty/current-theme.conf << EOF
# Faelight Forest - $theme theme
# Generated by theme-switch.sh

# Basic colors
foreground           $text
background           $bg
selection_background $accent
selection_foreground $bg

# Cursor
cursor               $primary
cursor_text_color    $bg

# URL underline color
url_color            $secondary

# Tab bar
active_tab_foreground   $bg
active_tab_background   $accent
inactive_tab_foreground $text
inactive_tab_background $comment

# The basic 16 colors
# Black
color0  $bg
color8  $comment

# Red
color1  #c94c4c
color9  #e06c75

# Green
color2  $secondary
color10 $accent

# Yellow
color3  #e8b563
color11 #e5c07b

# Blue
color4  $primary
color12 $primary

# Magenta
color5  #c678dd
color13 #e06c75

# Cyan
color6  $primary
color14 $secondary

# White
color7  $text
color15 #ffffff
EOF

    # Reload Kitty
    killall -SIGUSR1 kitty 2>/dev/null || true
    
    log_success "Kitty themed"
}

# Apply Mako theme
apply_mako() {
    local theme=$1
    log_info "Applying Mako notifications..."
    
    local bg=$(get_color "$theme" "surface")
    local text=$(get_color "$theme" "text")
    local border=$(get_color "$theme" "primary")
    
    # Update Mako config
    if [[ "$theme" == "dark" ]]; then
        sed -i "s/background-color=.*/background-color=#2e6146E6/" ~/.config/mako/config
        sed -i "s/text-color=.*/text-color=#e8f5d5/" ~/.config/mako/config
        sed -i "s/border-color=.*/border-color=#5bb7a5/" ~/.config/mako/config
    else
        sed -i "s/background-color=.*/background-color=#e0ede6E6/" ~/.config/mako/config
        sed -i "s/text-color=.*/text-color=#1a3a2d/" ~/.config/mako/config
        sed -i "s/border-color=.*/border-color=#2d8872/" ~/.config/mako/config
    fi
    
    # Reload Mako
    killall mako 2>/dev/null || true
    mako &
    disown
    
    log_success "Mako themed"
}

# Apply GTK theme
apply_gtk() {
    local theme=$1
    log_info "Applying GTK theme..."
    
    if [[ "$theme" == "dark" ]]; then
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
        gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
    else
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
        gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'
    fi
    
    log_success "GTK themed"
}

# Main theme application
apply_theme() {
    local theme=$1
    
    log_info "Switching to Faelight Forest $theme..."
    echo
    
    # Apply to each component
    apply_hyprland "$theme"
    apply_kitty "$theme"
    apply_mako "$theme"
    apply_gtk "$theme"
    
    # Save current theme
    echo "$theme" > "$CURRENT_FILE"
    
    echo
    log_success "Theme switched to $theme!"
    
    # Send notification
    notify-send "🌲 Faelight Forest" "Theme switched to $theme" -t 3000
}

# Get current theme
get_current_theme() {
    if [[ -f "$CURRENT_FILE" ]]; then
        cat "$CURRENT_FILE"
    else
        echo "dark"  # Default
    fi
}

# Main logic
case "${1:-toggle}" in
    dark)
        apply_theme "dark"
        ;;
    light)
        apply_theme "light"
        ;;
    toggle)
        current=$(get_current_theme)
        if [[ "$current" == "dark" ]]; then
            apply_theme "light"
        else
            apply_theme "dark"
        fi
        ;;
    status)
        current=$(get_current_theme)
        echo "Current theme: $current"
        ;;
    *)
        echo "Usage: $0 [dark|light|toggle|status]"
        exit 1
        ;;
esac
